apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: frontend
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx 